services:
  pocketId:
    image: ghcr.io/pocket-id/pocket-id:v1.16.0@sha256:f8cde808e8e840acda25683fc2168e0206e3f3fb1a48cca89d211aafd87eaeef
    restart: unless-stopped
    ports:
      - 1411:1411
    environment:
      APP_URL: http://localhost:1411
    volumes:
      - "pocketId_data:/app/data"

  traefik:
    image: "traefik:v3.7.14@sha256:e849695bc5c317da0cec22bfee4794fd9e15871fe554f864d31b625983e883ff"
    ports:
      - "9080:80"
      - "8080:8080"
    extra_hosts:
      - "localhost:172.17.0.1" # To make OIDC discovery work correctly
    volumes:
      - "../configs/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "../configs/http.yml:/etc/traefik/configs/http.yml:ro"
      - "../..:/plugins-local/src/github.com/BlackDark/gatepost:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    env_file:
      - ./.env

  whoami:
    image: "traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44"

volumes:
  pocketId_data:
