services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.8.0@sha256:b0f60d489d51c5d113390bdf5461d4c06e6051be026c05549f2e1e10ec352bcc
    restart: unless-stopped
    ports:
      - "8000:8080"
    environment:
      KC_HOSTNAME: "http://127-0-0-1.sslip.io:8000"
      KC_DB_URL: jdbc:postgresql://keycloak_postgres:5432/keycloak
      KC_DB: postgres
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    volumes:
      - "./master-realm.json:/opt/keycloak/data/import/master-realm.json:ro"
    depends_on:
      - keycloak_postgres
    command: ['start-dev', '--import-realm']

  keycloak_postgres:
    image: postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data

  traefik:
    image: "traefik:v3.7.14@sha256:e849695bc5c317da0cec22bfee4794fd9e15871fe554f864d31b625983e883ff"
    ports:
      - "9080:80"
      - "8080:8080"
    extra_hosts:
      - "127-0-0-1.sslip.io:172.17.0.1" # To make OIDC discovery work correctly
    volumes:
      - "../configs/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "../configs/http.yml:/etc/traefik/configs/http.yml:ro"
      - "../..:/plugins-local/src/github.com/BlackDark/gatepost:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      PROVIDER_URL: http://127-0-0-1.sslip.io:8000/realms/master
      CLIENT_ID: traefik
      CLIENT_SECRET: LQslcjK8ZeRrrhW7jKaFUUous9W5QvCr
      VALIDATE_AUDIENCE: true

  whoami:
    image: "traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44"

volumes:
  keycloak_postgres_data:
