services:
  logto:
    depends_on:
      logto_postgres:
        condition: service_healthy
    image: svhd/logto:latest@sha256:847cdd2759ad60f61b9733af0ea352183c805681dff5c9f8140a80f52d8e1340
    entrypoint: ["sh", "-c", "npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgres://postgres:postgres@logto_postgres:5432/logto
      - ENDPOINT
      - ADMIN_ENDPOINT
  logto_postgres:
    image: postgres:17-alpine@sha256:b0f9560a2de083e2cc7382e75f808c7381a32852a7ec49117deedb300e552b24
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - logto_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  traefik:
    image: "traefik:v3.7.14@sha256:e849695bc5c317da0cec22bfee4794fd9e15871fe554f864d31b625983e883ff"
    ports:
      - "9080:80"
      - "8080:8080"
    extra_hosts:
      - "127-0-0-1.sslip.io:172.17.0.1" # To make OIDC discovery work correctly
    volumes:
      - "../configs/traefik-config.yml:/etc/traefik/traefik.yml:ro"
      - "../configs/http.yml:/etc/traefik/configs/http.yml:ro"
      - "../..:/plugins-local/src/github.com/BlackDark/gatepost:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      PROVIDER_URL: http://127-0-0-1.sslip.io:3001/oidc
      CLIENT_ID: jgmgnr8u8vjfiris276nm
      CLIENT_SECRET: RqqG1VswoFZM6wDqrqFAdrwIrnTjOgKP
      VALIDATE_AUDIENCE: true

  whoami:
    image: "traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44"

volumes:
  logto_postgres_data:
